version: "3.8"

services:
  backend-wsgi:
    image: ${CMS_BACKEND_IMAGE}
    volumes:
      - django_static_volume:/home/app/cms/django_static/
      - files_backend_volume:/opt/patrocinio/
    command: gunicorn api_patrocinio.wsgi:application --bind 0.0.0.0:8000 --workers 4
    configs:
      - source: email_confirmation_message_template
        target: /home/app/cms/templates/account/email/email_confirmation_message.html
      - source: email_confirmation_signup_message_template
        target: /home/app/cms/templates/account/email/email_confirmation_signup_message.html
      - source: password_reset_key_message_template
        target: /home/app/cms/templates/account/email/password_reset_key_message.html
      - source: new_request_template
        target: /home/app/cms/templates/notifications/new_request.html
      - source: request_accepted_template
        target: /home/app/cms/templates/notifications/request_accepted.html
      - source: request_rejected_template
        target: /home/app/cms/templates/notifications/request_rejected.html
      - source: terms_and_policies_template
        target: /home/app/cms/terms_and_policies/terms_and_policies.md
    env_file:
      - ${CMS_BACKEND_ENV_FILE}
    depends_on:
      - db
    hostname: appserver
    networks:
      - proyecto-patrocinio
    deploy:
      replicas: 1

  backend-asgi:
    image: ${CMS_BACKEND_IMAGE}
    command: daphne -b 0.0.0.0 -p 8001 api_patrocinio.asgi:application
    env_file:
      - ${CMS_BACKEND_ENV_FILE}
    depends_on:
      - redis
      - backend-wsgi
    hostname: appserver
    networks:
      - proyecto-patrocinio
    deploy:
      replicas: 1

  db:
    image: "postgres:15-alpine"
    env_file: ${CMS_POSTGRES_ENV_FILE}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    hostname: databaseserver
    networks:
      - proyecto-patrocinio
    deploy:
      replicas: 1

  frontend:
    image: ${CMS_FRONTEND_IMAGE}
    configs:
      - source: frontend_env
        target: /app/.env
      - source: logo
        target: /app/public/favicon.ico
    depends_on: 
        - backend-wsgi
        - backend-asgi
    hostname: frontend
    networks:
      - proyecto-patrocinio
    deploy:
      replicas: 1

  nginx:
    image: "nginx:1.21.0-alpine"
    ports:
        - ${CMS_PROXY_PORT}:80
    volumes:
        - django_static_volume:/usr/share/nginx/staticfiles/cms/django/
    configs:
        - source: nginx_config
          target: /etc/nginx/conf.d/default.conf
    depends_on: 
        - frontend
    hostname: nginxserver
    networks:
      - proyecto-patrocinio
    deploy:
      replicas: 1

  redis:
    image: "redis:alpine"
    networks:
      - proyecto-patrocinio
    deploy:
      replicas: 1


configs:
  nginx_config:
    file: ${CMS_NGINX_CONFIG_FILE}
  frontend_env:
    file: ${CMS_FRONTEND_ENV_FILE}
  logo:
    file: ${CMS_LOGO_FILE}
  email_confirmation_message_template:
    file: ${CMS_TEMPLATES_ACCOUNT_PATH}/email_confirmation_message.html
  email_confirmation_signup_message_template:
    file: ${CMS_TEMPLATES_ACCOUNT_PATH}/email_confirmation_signup_message.html
  password_reset_key_message_template:
    file: ${CMS_TEMPLATES_ACCOUNT_PATH}/password_reset_key_message.html
  new_request_template:
    file: ${CMS_TEMPLATES_NOTIFICATION_PATH}/new_request.html
  request_accepted_template:
    file: ${CMS_TEMPLATES_NOTIFICATION_PATH}/request_accepted.html
  request_rejected_template:
    file: ${CMS_TEMPLATES_NOTIFICATION_PATH}/request_rejected.html
  terms_and_policies_template:
    file: ${CMS_TERMS_AND_POLICIES_FILE}

volumes:
  postgres_data_prod:
  django_static_volume:
  files_backend_volume:


networks:
  proyecto-patrocinio:
    name: proyecto-patrocinio
    driver: overlay
