version: "3.8"

services:
  backend-wsgi:
    restart: on-failure
    restart_limit: 10
    image: ${CMS_BACKEND_IMAGE}
    volumes:
      - django_static_volume:/home/app/cms/django_static/
    command: gunicorn api_patrocinio.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 4
    expose:
      - 8000 
    env_file:
      - ${CMS_BACKEND_ENV_FILE}
    environment:
      - SECRET_KEY=/run/secrets/secret_key
      - SQL_PASSWORD=/run/secrets/postgres_password
      - EMAIL_HOST_PASSWORD=/run/secrets/email_host_password
      - DJANGO_SUPERUSER_USERNAME=/run/secrets/django_superuser_username
      - DJANGO_SUPERUSER_PASSWORD=/run/secrets/django_superuser_password
      - DJANGO_SUPERUSER_EMAIL=/run/secrets/django_superuser_email
    depends_on:
      - db
    hostname: appserver
    networks:
      - proyecto-patrocinio
    secrets:
      - secret_key
      - postgres_password
      - email_host_password
      - django_superuser_username
      - django_superuser_password
      - django_superuser_email
    deploy:
      replicas: 1

  backend-asgi:
    restart: on-failure
    restart_limit: 10
    image: ${CMS_BACKEND_IMAGE}
    command: daphne -b 0.0.0.0 -p 8001 api_patrocinio.asgi:application
    expose:
      - 8001
    env_file:
      - ${CMS_BACKEND_ENV_FILE}
    environment:
      - SECRET_KEY=/run/secrets/secret_key
      - SQL_PASSWORD=/run/secrets/postgres_password
      - EMAIL_HOST_PASSWORD=/run/secrets/email_host_password
      - DJANGO_SUPERUSER_USERNAME=/run/secrets/django_superuser_username
      - DJANGO_SUPERUSER_PASSWORD=/run/secrets/django_superuser_password
      - DJANGO_SUPERUSER_EMAIL=/run/secrets/django_superuser_email
    depends_on:
      - redis
    hostname: appserver
    networks:
      - proyecto-patrocinio
    secrets:
      - secret_key
      - postgres_password
      - email_host_password
      - django_superuser_username
      - django_superuser_password
      - django_superuser_email
    deploy:
      replicas: 1

  db:
    restart: on-failure
    restart_limit: 10
    image: postgres:15-alpine 
    env_file: ${CMS_POSTGRES_ENV_FILE}
    environment:
      - POSTGRES_PASSWORD=/run/secrets/postgres_password
    expose:
      - 5432
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    hostname: databaseserver
    networks:
      - proyecto-patrocinio
    secrets:
      - postgres_password
    deploy:
      replicas: 1

  nginx:
    restart: on-failure
    restart_limit: 10
    image: ${CMS_FRONTEND_IMAGE}
    ports:
        - ${CMS_PROXY_PORT}:80
    volumes:
        - django_static_volume:/usr/share/nginx/staticfiles/cms/django/
        - react_static_volume:/usr/share/nginx/staticfiles/cms/react/
    configs:
        - source: nginx-config
        - target: /etc/nginx/conf.d/default.conf
    depends_on: 
        - backend-wsgi
        - backend-asgi
    hostname: nginxserver
    networks:
      - proyecto-patrocinio
    deploy:
      replicas: 1

  redis:
    restart: on-failure
    restart_limit: 10
    image: "redis:alpine"
    container_name: redis_server
    expose:
      - 6379
    networks:
      - proyecto-patrocinio
    deploy:
      replicas: 1

secrets:
  secret_key:
    external: true
    name: secret_key
  postgres_password:
    external: true
    name: postgres_password
  email_host_password:
    external: true
    name: email_host_password
  django_superuser_username:
    external: true
    name: django_superuser_username
  django_superuser_password:
    external: true
    name: django_superuser_password
  django_superuser_email:
    external: true
    name: django_superuser_email


configs:
  nginx-config:
    file: ${CMS_NGINX_CONFIG_FILE}


volumes:
  postgres_data_prod:
  django_static_volume:
  react_static_volume:


networks:
  proyecto-patrocinio:
    name: proyecto-patrocinio
    driver: overlay
